services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pinjamkelas_app
    ports:
      - "8000:80"  # Akses Laravel via http://localhost:8000
    volumes:
      - /mnt/c/laragon/www/pinjamkelas:/var/www/html
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: pinjamkelas_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: pinjamkelas
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
